# Generated by Django 5.2.8 on 2026-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_collection_image_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="year",
            field=models.IntegerField(blank=True, null=True, verbose_name="year"),
        ),
    ]
